<?php

namespace AppBundle\Repository;

/**
 * EsquisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EsquisseRepository extends \Doctrine\ORM\EntityRepository
{
}
