<?php

namespace AppBundle\Repository;

/**
 * TatooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TattooRepository extends \Doctrine\ORM\EntityRepository
{
}
