imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.articles_images: /uploads/images/articles

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    design:
      form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']

    entities:
        Article:
            class: AppBundle\Entity\Article
            list:
              fields:
                    - id
                    - { property: 'title', type: 'text' }
                    - { property: 'text', type: 'text' }
                    - { property: 'author'}
                    - { property: 'category'}
                    - { property: 'image', type: 'image', base_path: %app.path.articles_images% }
            show:
              fields:
                    - { property: 'image', type: 'image', base_path: %app.path.articles_images% }
            form:
              fields:
                  - { property: 'title', type: 'text' }
                  - { property: 'text', type: 'textarea' }
                  - { property: 'author'}
                  - { property: 'category'}
                  - { property: 'imageFile', type: 'vich_file' }
        Person:
            class: AppBundle\Entity\Person
        Image:
            class: AppBundle\Entity\Image

vich_uploader:
    db_driver: orm
    mappings:
            articles_images:
                uri_prefix:         "%app.path.articles_images%"
                upload_destination: "%kernel.root_dir%/../web/uploads/images/articles"
