easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   admin
    schemes: [https]

api:
    resource: "@AppBundle/Api/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    schemes: [https]
