security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
             memory:
                users:
                    admin:
                        password: $2y$12$m4FKZlXYXG06LXK9P/mYP.hSM3d7MC22WyOMNRvQbYjW/hungqVWy
                        roles: 'ROLE_ADMIN'

    firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false

            main:
                anonymous: ~
                http_basic: ~
                stateless:  true
                provider: in_memory

    access_control:
                - { path: ^/admin, roles: ROLE_ADMIN }
